### ISSUE TITLE
Will CHIP Pro's WiFi support monitor mode?

### ISSUE THREAD

**Issue by pandalion98** [NextThingCo/CHIP_Pro-Hardware#1]

**Comment by JarrettR** [comment]
A quick look at the datasheet shows that it uses the same Realtek 8723BS chip as the original CHIP.

So if you can use monitor mode in the original, you can use it in this. The forum there here suggests that it is possible:
https://bbs.nextthing.co/t/pocketchip-monitor-mode-on-internal-wifi-probe-requests-working/5509

**Comment by pandalion98** [comment]
@JarrettR Yeah, I did notice that in the datasheet. I was wondering if it was somehow disabled in the firmware or something.

Thanks for clarifying 😄
