### ISSUE TITLE
SDA/SCL in CHIP Pro Datasheet Image

### ISSUE THREAD

**Issue by Shadyman** [NextThingCo/CHIP_Pro-Hardware#11]
CHIP_PRO_Datasheet_v1.03.pdf Figure 5.1-1 seems to require updating for the  #8 SDA/SCL issue. 

Table 5.2.1 defines Pin 12 as PB15 and Pin 11 as PB16.
Table 5.3.1 (Mux Fuctions) then defines PB15 as SCK and PB16 as SDA.

So between the two tables, we get:
Pin 11 == PB16 == SDA
Pin 12 == PB15 == SCK

It seems like the labels of PB15 and PB16 need to be swapped on Figure 5.1-1?

The image located at https://www.getchip.com/pages/chippro#undefined1 under "Pinouts" (aka https://cdn.shopify.com/s/files/1/1065/9514/t/41/assets/chippro_pinout.png?14806488518031960679 ) seems to be correct according to the in the document.

**Comment by blinkengus** [comment]
@Shadyman Good catch, and correct -- thank you for letting us know! Will push a revision shortly.

**Comment by blinkengus** [comment]
After looking into it, the v1.03 datasheet's figures are correct, it is the tables which need to be updated, as well as the figure on the pinout portion of the website.

correct pinout is as shown in the datasheet 1.03 figures:
Pin 11 == PB15
Pin 12 == PB16

**Comment by Shadyman** [comment]
Good to know. I only stumbled across it after writing up a symbol for 
the gEDA/PCB suite straight from the datasheet.

Thanks!

**Comment by blinkengus** [comment]
table 5.2.1 updated, and v1.04 datasheet pushed, issue closed. thanks for alerting us!
