### ISSUE TITLE
Pin descriptions missing (TEMPSENSE/IPSOUT/PWRON)

### ISSUE THREAD

**Issue by bhusang** [NextThingCo/CHIP_Pro-Hardware#2]
Perusing the datasheet, I find that the 3 pins are barely mentioned. They do not appear in the pin description section (4.3 Detailed Pin/Signal Description). I can infer the operation of PWRON from one line in section 3: A power-button pulls the PWRON pin to ground to turn on the module. Nowhere else does the information about that pin appear (i.e. is it momentary or static?). The IPSOUT appears to be the output of the AXP209. Also TEMPSENSE appears connected to the TS pin on the AXP209 but that was only found by chasing down the net in section 8 (Schematics).

**Comment by bhusang** [comment]
<bump> Hello, NTC? Any update?

I get that TEMPSENSE or BATTTEMP is for monitoring the LiPo battery temperature.

**Comment by jordanlance** [comment]
Almost bought the pro board.
Luckily came across this repo; its of course not in NTC interest to fix these issues.
Guess I'll be looking for another board that is truly opensource and documented well

**Comment by blinkengus** [comment]
@bhusang thanks for calling out these omissions on the documentation. They have been flagged for update with our next file release. In the mean time:

PWRON is documented in the AXP209 PMIC's datasheet. It is pulled up through internal 100K resistors. to the PMIC's APS circuit. The power-on interrupt is asserted by a momentary pull to logic-low. A longer press-and-hold function on the same pin can be defined either through the system or in the register settings of the AXP209.

IPSOUT is also described in the AXP209 documentation, and is the "Intelligent Power Select" output which will pass through BAT, CHGIN, or VBUS_USB based on the operating logic set in the AXP209. On CHIP Pro, we suggest attaching any secondary DCDC power supplies to IPSOUT.

TEMPSENSE is also documented in the AXP209's datasheet, and is suggested for use with a 10KΩ 1% NTC Thermistor, used to set battery high and low temperature limits before the AXP209 throttles charge or discharge current. For development purposes, TS can also be pulled to ground, or disabled in software (allowing it to function as an extra ADC circuit, accessible through the AXP209).
