### ISSUE TITLE
Nothing said about WiFi module

### ISSUE THREAD

**Issue by socketpair** [NextThingCo/CHIP_Pro-Hardware#3]

**Comment by Kalyse** [comment]
As above. 

Specifically what the chip is, and also I'm looking to know if it supports MONITOR/PROMISCUOUS mode.

**Comment by pandalion98** [comment]
I recommend checking #1.

**Comment by blinkengus** [comment]
Thank you all for flagging this omission -- the Wifi/BT combo radio on CHIP Pro is a modularized version of the Realtek 8723DS, a die-shrunk version of the Realtek 8723BS used on our earlier board C.H.I.P. We will include Wifi documentation in the next datasheet update.
