### ISSUE TITLE
VBUS and GND swapped in application diagram

### ISSUE THREAD

**Issue by DurandA** [NextThingCo/CHIP_Pro-Hardware#4]
Pin 50 (VBUS) and pin 1 (GND) are swapped in the application diagram.
According to the datasheet pin 50 is VBUS while pin 1 is GND. In the application diagram, pin 1 is VBUS and pin 50 GND (header pin next to pin 1 is connected to GND though).

Can you confirm that the datasheet is right?

**Comment by Flexshot** [comment]
Thanks for pointing out this issue. I'll discuss this during our next documentation meeting after the Holiday so we can push out an update soon.

**Comment by blinkengus** [comment]
@DurandA yes, the datasheet is correct. Thank you for pointing out our error on the application diagram, which incorrectly abstracts the layout of CHIP Pro's pins. I'll be updating it shortly.
