### ISSUE TITLE
Software PWM

### ISSUE THREAD

**Issue by sdaitzman** [NextThingCo/CHIP_Pro-Hardware#6]
I am considering CHIP Pro for a hardware product currently in development. We need more than two PWM pins. Is CHIP able to do software PWM on GPIO pins?

**Comment by blinkengus** [comment]
@sdaitzman softPWM is possible, however for timing-critical modulations such as motor positioning, we suggest adding an external MCU or PWM driver (I2C servo drivers, etc.) which will not lead or lag based on CPU thread prioritization the way a softPWM'd pin will.
