### ISSUE TITLE
No full schematics in eagle or other format?

### ISSUE THREAD

**Issue by jordanlance** [NextThingCo/CHIP_Pro-Hardware#7]
Just the PDF? 
No full schematics in eagle or other format?
Did I miss them,
this seems like a "hardware repo" with incomplete source files.

Assuming full source of eagle or other files is not available? 
I want to modify the board for a personal project but it seems I have to look for an other solution that is truly opensource or am I at fault and can anyone point me the right file?

**Comment by blinkengus** [comment]
@jordanlance CHIP Pro full source files (in Orcad Allegro .DSN/.SCH format) will be released soon, after modular compliance and interoperability certification is completed.

**Comment by jordanlance** [comment]
Sorry for my harsh words, it was a bit frustration with "opensource" boards many are not.
Do you have an ETA for when they will be delivered? I would like to learn EDA and try adding an internal speaker and IR on board lateron.

**Comment by blinkengus** [comment]
Should be in the next few weeks, @jordanlance
