### ISSUE TITLE
SDA and SCK swapped in documentation and footprint

### ISSUE THREAD

**Issue by DurandA** [NextThingCo/CHIP_Pro-Hardware#8]
Pin PB15 (TWI1-SDA) and pin PB16 (TWI1-SCK) are swapped in the documentation (CHIP_PRO_Datasheet_v1.0.pdf and CHIPPro-pinout.png) and on footprint (at least EAGLE version).

Now I have to cut traces on my fresh PCBs. :weary:

**Comment by blinkengus** [comment]
@DurandA I fixed the EAGLE footprint, pulled the others while we get them repaired, and did my best to clean up mentions of the old (now incorrect) pinout. Note that Photos in the datasheet and manual still need to be re-shot and updated, however all text and pinout diagrams should now be correct, and align with the printed documentation that came with the devkit as well as what's printed on the Pro module itself. Apologies for old data that slipped through initial release.
