### ISSUE TITLE
Incorrect GND pin assignment in datasheet (table 4-1)

### ISSUE THREAD

**Issue by bhusang** [NextThingCo/CHIP_Pro-Hardware#9]
Table 4-1: pin assignment lists pin 50 as GND but pin 50 is also assigned to VBUS earlier in the table as well as in the embedded picture in section 6.

This is related to issue #4.

Seriously your documentation needs scrubbing and quickly, don't you think?

**Comment by jordanlance** [comment]
Would also really like to have a correct documentation to build a pcb for a home project.

**Comment by blinkengus** [comment]
Updated PDF to correct errata, and will be releasing further clarifications and edits to datasheet early next week.
